/*
 *      Copyright 2009 Battams, Derek
 *       
 *       Licensed under the Apache License, Version 2.0 (the "License");
 *       you may not use this file except in compliance with the License.
 *       You may obtain a copy of the License at
 *
 *          http://www.apache.org/licenses/LICENSE-2.0
 *
 *       Unless required by applicable law or agreed to in writing, software
 *       distributed under the License is distributed on an "AS IS" BASIS,
 *       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *       See the License for the specific language governing permissions and
 *       limitations under the License.
 */
package com.google.code.sagetvaddons.sagealert.server;

import gkusnick.sagetv.api.SystemMessageAPI;

import com.google.code.sagetvaddons.sagealert.client.SageEventMetaData;

/**
 * A SageEvent that signifies that a new system message has been generated by SageTV
 * @author dbattams
 * @version $Id$
 */
final class SystemMessageEvent implements SageEvent {
	static final SageEventMetaData EVENT_METADATA = new SageEventMetaData(SystemMessageEvent.class.getCanonicalName(), "Alert when a new system message is generated by SageTV.");
	static private final String[] SYS_MSG_TYPE = new String[] {"", "INFO", "WARNING", "ERROR"};
	
	private SystemMessageAPI.SystemMessage msg;
	
	/**
	 * ctor
	 * @param msg The SystemMessage that caused this event; the event's source
	 */
	SystemMessageEvent(SystemMessageAPI.SystemMessage msg) {
		this.msg = msg;
	}
	
	/* (non-Javadoc)
	 * @see com.google.code.sagetvaddons.sagealert.server.SageEvent#getEventMetaData()
	 */
	@Override
	public SageEventMetaData getEventMetaData() {
		return EVENT_METADATA;
	}

	/* (non-Javadoc)
	 * @see com.google.code.sagetvaddons.sagealert.server.SageEvent#getLongDescription()
	 */
	@Override
	public String getLongDescription() {
		return SYS_MSG_TYPE[msg.GetSystemMessageLevel()] + ": " + msg.GetSystemMessageString();
	}

	/* (non-Javadoc)
	 * @see com.google.code.sagetvaddons.sagealert.server.SageEvent#getMediumDescription()
	 */
	@Override
	public String getMediumDescription() {
		return SYS_MSG_TYPE[msg.GetSystemMessageLevel()] + ": " + msg.GetSystemMessageTypeName();
	}

	/* (non-Javadoc)
	 * @see com.google.code.sagetvaddons.sagealert.server.SageEvent#getShortDescription()
	 */
	@Override
	public String getShortDescription() {
		return getMediumDescription();
	}

	/* (non-Javadoc)
	 * @see com.google.code.sagetvaddons.sagealert.server.SageEvent#getSource()
	 */
	@Override
	public SystemMessageAPI.SystemMessage getSource() {
		return msg;
	}

	/* (non-Javadoc)
	 * @see com.google.code.sagetvaddons.sagealert.server.SageEvent#getSubject()
	 */
	@Override
	public String getSubject() {
		return "New system message generated...";
	}

}
